name: FT_PRINTF Tests

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop

jobs:
  ft_printf_tester:
    name: Run FT_PRINTF Tester
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Install Required Packages
        run: sudo apt update && sudo apt install -y make gcc

      - name: Set Terminal Environment
        run: echo "TERM=xterm" >> $GITHUB_ENV

      - name: Run FT_PRINTF Tests
        run: make test

  norminette_check:
    name: Run Norminette
    runs-on: ubuntu-latest
    needs: ft_printf_tester  # Esto asegura que la ejecución de Norminette dependa de que el trabajo de FT_PRINTF Tests haya terminado
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          submodules: true  # Asegura que los submódulos se descarguen

      - name: Install Norminette
        run: |
          git clone https://github.com/42School/norminette.git
          cd norminette
          sudo make install

      - name: Run Norminette
        run: |
          norminette src/ include/